# Generated by Django 5.0.6 on 2024-07-24 05:31

import post.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="picture",
            field=models.ImageField(
                default="Tagtales\\static\\images\\hashtag.png",
                upload_to=post.models.user_directory_path,
                verbose_name="Picture",
            ),
        ),
    ]
